### ISSUE TITLE
Not working without GAPPS / micoG ?

### ISSUE THREAD

**Issue by Matthias84** [SecUSo/privacy-friendly-wifi-manager#16] opened 2019-02-05 11:04 UTC
Hi, the discovery of GSM cell towers seem to use only the Android location feature. This feature requires Google Apps Frameworks, or at least an MicroG replacement that doesn't ship with LineageOS.

But there seems to be an easier way that makes use of the TelephonyManager API, that comes with AOSP.

**Comment by mat-de-mystify** [comment] 2019-02-09 11:02
Works OK for me on lineage with out gapps, I'm running a nightly version of android 7

**Comment by selurvedu** [comment] 2019-02-18 12:48
@Matthias84, works for me – I use UnifiedNlp without microG or GApps. Try using it if you haven't tried yet.

**Comment by wangongtsen** [comment] 2019-02-18 14:52
@selurvedu, what OS version do you use?

**Comment by selurvedu** [comment] 2019-02-18 17:53
@wangongtsen, I use LineageOS 13.0 and 14.1. The latter one is an official build, the former one is not – it is a hacky custom build for a model that was not officially supported when the firmware was released.

**Comment by Kamuno** [comment] 2019-03-08 11:13
Since this seems to be no Issue and the only thing remaining is already mentioned I'll close this.

Duplicate of #21

**Closed by Kamuno** 2019-03-08 11:13 UTC
